import { mkdir, writeFile, readFile } from "fs/promises";
import { join } from "path";
import { existsSync } from "fs";

function generateConfig(resourceClass: string) {
  return `# Auto-generated by lemonx — AI-powered test generation, execution, and self-healing fixes
#
# This config runs on a CircleCI machine runner that has the lemon.test platform
# pre-installed. No webhook, no tunnel, no external server needed.

version: 2.1

workflows:
  ai-test-and-fix:
    jobs:
      - ai-test-loop:
          filters:
            branches:
              ignore: main

jobs:
  ai-test-loop:
    machine: true
    resource_class: ${resourceClass}
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Run lemon.test AI test-fix loop
          command: |
            echo "🍋 Running AI test generation, execution, and self-healing fixes..."
            cd ~/project

            RESPONSE=$(npx tsx /home/circleci/lemon/src/index.ts 2>&1)

            echo "$RESPONSE"

            if echo "$RESPONSE" | grep -q "⚠️.*Max iterations reached"; then
              echo "⚠️  AI could not fix all tests within the iteration limit"
              exit 1
            fi

            if echo "$RESPONSE" | grep -q "❌"; then
              echo "❌ AI test loop failed"
              exit 1
            fi

            echo "✅ All tests passed"

  ai-generate-tests:
    machine: true
    resource_class: ${resourceClass}
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Generate AI tests
          command: |
            echo "🍋 Generating tests..."
            npx tsx /home/circleci/lemon/src/index.ts --generate-only

  ai-run-tests:
    machine: true
    resource_class: ${resourceClass}
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Run existing tests
          command: |
            echo "🍋 Running tests..."
            npx vitest run --reporter=verbose
`;
}

function parseArgs(args: string[]) {
  let targetDir = process.cwd();
  let resourceClass = "";

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--runner" && args[i + 1]) {
      resourceClass = args[++i];
    } else if (!args[i].startsWith("--")) {
      targetDir = args[i];
    }
  }

  return { targetDir, resourceClass };
}

export async function init(args: string[] = []) {
  const { targetDir, resourceClass } = parseArgs(args);
  const circleciDir = join(targetDir, ".circleci");

  console.log("🍋 lemonx init — setting up CircleCI AI test integration\n");

  if (!existsSync(targetDir)) {
    console.error(`❌ Directory not found: ${targetDir}`);
    process.exit(1);
  }

  if (!resourceClass) {
    console.error("❌ Missing required --runner flag.");
    console.error("   Usage: npx lemonx init [dir] --runner <namespace>/<resource-class>");
    console.error("   Example: npx lemonx init ./my-repo --runner my-org/lemon-runner");
    process.exit(1);
  }

  if (!resourceClass.includes("/")) {
    console.error(`❌ Invalid runner resource class: "${resourceClass}"`);
    console.error("   Expected format: <namespace>/<resource-class>");
    console.error("   Example: my-org/lemon-runner");
    process.exit(1);
  }

  await mkdir(circleciDir, { recursive: true });

  const configPath = join(circleciDir, "config.yml");
  const exists = existsSync(configPath);

  if (exists) {
    const existing = await readFile(configPath, "utf-8");
    if (existing.includes("lemonx") || existing.includes("resource_class")) {
      console.log("⚠️  CircleCI config already contains lemonx integration. Skipping.");
      console.log(`   Config: ${configPath}`);
      console.log(`   Runner: ${resourceClass}`);
      return;
    }
    console.log(`⚠️  Existing CircleCI config found at: ${configPath}`);
    console.log("   Back it up before overwriting.\n");
  }

  const config = generateConfig(resourceClass);
  await writeFile(configPath, config, "utf-8");
  console.log(`✅ CircleCI config written to: ${configPath}`);
  console.log(`   Runner: ${resourceClass}`);

  console.log("\nNext steps:");
  console.log("1. Start the lemon.test machine runner:");
  console.log("   docker compose -f docker-compose.runner.yml up -d");
  console.log("\n2. Push to any branch (not main) and CircleCI will trigger the AI test loop!");
}
